# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iS7xNGSU-Cv4wOQcO9aD-HDhLkLXpUOt
"""

def futbolchi_jamoa(futbolchi_ismi):
  if futbolchi_ismi == "Lionel Messi":
    return "Paris Saint-Germain"
  elif futbolchi_ismi == "Cristiano Ronaldo":
    return "Al Nassr"
  elif futbolchi_ismi == "Neymar Jr":
    return "Al Hilal"
  elif futbolchi_ismi == "Kylian Mbappe":
    return "Paris Saint-Germain"
  elif futbolchi_ismi == "Robert Lewandowski":
    return "FC Barcelona"
  elif futbolchi_ismi == "Mohamed Salah":
    return "Liverpool"
  elif futbolchi_ismi == "Erling Haaland":
    return "Manchester City"
  elif futbolchi_ismi == "Zinedine Zidane":
    return "O'yinni yakunlagan"
  else:
    return "Bu futbolchi hozirda faol emas"

futbolchi_ism = input("Futbolchi ismini kiriting (familiyasiz): ")
natija = futbolchi_jamoa(futbolchi_ism)
print(natija)